name: Build JOSE Draft 📃
on:
  push:
    branches:
    - jose
jobs:
  paper:
    name: Build Paper Draft 🔧
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code 🛎️
      uses: actions/checkout@v2
    - name: Build draft LaTeX 📝
      uses: docker://openjournals/paperdraft:latest
      with:
        args: -k paper/paper.md
      env:
        GIT_SHA: $GITHUB_SHA
        JOURNAL: jose
    - name: Build draft PDF 📝
      uses: openjournals/openjournals-draft-action@master
      with:
        journal: jose
        paper-path: paper/paper.md
    - name: Upload draft (PDF and LaTeX) 📤
      uses: actions/upload-artifact@v1
      with:
        name: jose-draft
        path: paper
